---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: tapiren
  namespace: default
  annotations:
    flux.weave.works/automated: "true"
spec:
  releaseName: tapiren
  chart:
    git: ssh://git@github.com/mikerm4n/flux-get-started
    ref: master
    path: charts/tapiren
  values:
    replicaCount: 1
    namespace: default
    configmap:
      enable: false
    deployment: {}
    image: bitnami/ghost:1.21.5-r0
    service:
      enabled: true
      name: 
      ports:
        - name: http
          port: 3333 
          targetPort: 3333
    ingress:
      enabled: true
      hosts:
        - adm1.tt.se/tapiren
        - traefik1.tt.se/tapiren
  
