---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: tapiren
  namespace: default
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: tapiren
  chart:
    git: ssh://git@github.com/weaveworks/flux-get-started
    ref: master
    path: charts/tapiren
  values:
    image: docker-registry.ad.tt.se/ttab/tapiren:prod    
